
version: '3'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/medify
      - SECRET_KEY=${SECRET_KEY:-your-super-secret-key-here-make-it-long-and-random}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - REFRESH_TOKEN_EXPIRE_DAYS=7
      - FRONTEND_URL=http://localhost:8080
      - BACKEND_URL=http://localhost:8000
    volumes:
      - ./static:/app/static
      - ./logs:/app/logs

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=medify
    ports:
      - "5432:5432"

volumes:
  postgres_data:
